{% set name = "jupyterlab-mathjax2" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1748fc09e18ef6f878670e400932dc3a08db012d97f4680c238a3a38f7af2461

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab >=4,<5
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyterlab/mathjax2-extension.*{{ version }}.*ok.*jupyterlab_mathjax2" labextensions
  requires:
    - pip
    - jupyterlab >=4.0
    - m2-grep  # [win]

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: A MathJax 2 Typesetting provider for JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab_mathjax2/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - fcollonval
    - jtpio
